package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/ForumHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

public final class ForumHolder implements org.omg.CORBA.portable.Streamable
{
	public fr.umlv.ir3.corba.sguincha.td2.Forum	value	= null;

	public ForumHolder ()
	{
	}

	public ForumHolder (fr.umlv.ir3.corba.sguincha.td2.Forum initialValue)
	{
		value = initialValue;
	}

	public void _read (org.omg.CORBA.portable.InputStream i)
	{
		value = fr.umlv.ir3.corba.sguincha.td2.ForumHelper.read (i);
	}

	public void _write (org.omg.CORBA.portable.OutputStream o)
	{
		fr.umlv.ir3.corba.sguincha.td2.ForumHelper.write (o , value);
	}

	public org.omg.CORBA.TypeCode _type ()
	{
		return fr.umlv.ir3.corba.sguincha.td2.ForumHelper.type ();
	}

}
