package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/ForumHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

abstract public class ForumHelper
{
	private static String	_id	= "IDL:td2/Forum:1.0";

	public static void insert (org.omg.CORBA.Any a, fr.umlv.ir3.corba.sguincha.td2.Forum that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out , that);
		a.read_value (out.create_input_stream () , type ());
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Forum extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode	__typeCode	= null;

	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (fr.umlv.ir3.corba.sguincha.td2.ForumHelper.id () , "Forum");
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Forum read (org.omg.CORBA.portable.InputStream istream)
	{
		return narrow (istream.read_Object (_ForumStub.class));
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, fr.umlv.ir3.corba.sguincha.td2.Forum value)
	{
		ostream.write_Object ((org.omg.CORBA.Object) value);
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Forum narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof fr.umlv.ir3.corba.sguincha.td2.Forum)
			return (fr.umlv.ir3.corba.sguincha.td2.Forum) obj;
		else if (!obj._is_a (id ()))
			throw new org.omg.CORBA.BAD_PARAM ();
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
			fr.umlv.ir3.corba.sguincha.td2._ForumStub stub = new fr.umlv.ir3.corba.sguincha.td2._ForumStub ();
			stub._set_delegate (delegate);
			return stub;
		}
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Forum unchecked_narrow (org.omg.CORBA.Object obj)
	{
		if (obj == null)
			return null;
		else if (obj instanceof fr.umlv.ir3.corba.sguincha.td2.Forum)
			return (fr.umlv.ir3.corba.sguincha.td2.Forum) obj;
		else
		{
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
			fr.umlv.ir3.corba.sguincha.td2._ForumStub stub = new fr.umlv.ir3.corba.sguincha.td2._ForumStub ();
			stub._set_delegate (delegate);
			return stub;
		}
	}

}
