package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/Forum.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15 octobre
 * 2004 14 h 06 CEST
 */

public interface Forum extends ForumOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Forum
