package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/ForumPOA.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15 octobre
 * 2004 14 h 06 CEST
 */

public abstract class ForumPOA extends org.omg.PortableServer.Servant implements fr.umlv.ir3.corba.sguincha.td2.ForumOperations, org.omg.CORBA.portable.InvokeHandler
{

	// Constructors

	private static java.util.Hashtable	_methods	= new java.util.Hashtable ();
	static
	{
		_methods.put ("_get_theme" , new java.lang.Integer (0));
		_methods.put ("_get_moderator" , new java.lang.Integer (1));
		_methods.put ("postMessage" , new java.lang.Integer (2));
		_methods.put ("getMessage" , new java.lang.Integer (3));
		_methods.put ("getMessages" , new java.lang.Integer (4));
		_methods.put ("removeMessage" , new java.lang.Integer (5));
	}

	/**
	 * @see org.omg.CORBA.portable.InvokeHandler#_invoke(java.lang.String, org.omg.CORBA.portable.InputStream, org.omg.CORBA.portable.ResponseHandler)
	 */
	public org.omg.CORBA.portable.OutputStream _invoke (String $method, org.omg.CORBA.portable.InputStream in, org.omg.CORBA.portable.ResponseHandler $rh)
	{
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get ($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue ())
		{
			case 0 : // td2/Forum/_get_theme
			{
				String $result = null;
				$result = this.theme ();
				out = $rh.createReply ();
				out.write_string ($result);
				break;
			}

			case 1 : // td2/Forum/_get_moderator
			{
				String $result = null;
				$result = this.moderator ();
				out = $rh.createReply ();
				out.write_string ($result);
				break;
			}

			case 2 : // td2/Forum/postMessage
			{
				fr.umlv.ir3.corba.sguincha.td2.Message m = fr.umlv.ir3.corba.sguincha.td2.MessageHelper.read (in);
				boolean $result = false;
				$result = this.postMessage (m);
				out = $rh.createReply ();
				out.write_boolean ($result);
				break;
			}

			case 3 : // td2/Forum/getMessage
			{
				String title = in.read_string ();
				fr.umlv.ir3.corba.sguincha.td2.Message $result = null;
				$result = this.getMessage (title);
				out = $rh.createReply ();
				fr.umlv.ir3.corba.sguincha.td2.MessageHelper.write (out , $result);
				break;
			}

			case 4 : // td2/Forum/getMessages
			{
				fr.umlv.ir3.corba.sguincha.td2.Message $result[] = null;
				$result = this.getMessages ();
				out = $rh.createReply ();
				fr.umlv.ir3.corba.sguincha.td2.MessageSetHelper.write (out , $result);
				break;
			}

			case 5 : // td2/Forum/removeMessage
			{
				String title = in.read_string ();
				boolean $result = false;
				$result = this.removeMessage (title);
				out = $rh.createReply ();
				out.write_boolean ($result);
				break;
			}

			default :
				throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String []	__ids	= {"IDL:td2/Forum:1.0"};

	/**
	 * @see org.omg.PortableServer.Servant#_all_interfaces(org.omg.PortableServer.POA, byte[])
	 */
	public String [] _all_interfaces (org.omg.PortableServer.POA poa, byte [] objectId)
	{
		return (String []) __ids.clone ();
	}

	/**
	 * @return the forum
	 */
	public Forum _this ()
	{
		return ForumHelper.narrow (super._this_object ());
	}

	/**
	 * @param orb
	 * @return a forum
	 */
	public Forum _this (org.omg.CORBA.ORB orb)
	{
		return ForumHelper.narrow (super._this_object (orb));
	}

} // class ForumPOA
