package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/ForumOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

public interface ForumOperations
{
	/**
	 * @return the theme
	 */
	String theme ();

	/**
	 * @return a String 
	 */
	String moderator ();

	/**
	 * @param m
	 * @return if the operation successfully or not
	 */
	boolean postMessage (fr.umlv.ir3.corba.sguincha.td2.Message m);

	/**
	 * @param title
	 * @return a message
	 */
	fr.umlv.ir3.corba.sguincha.td2.Message getMessage (String title);

	/**
	 * @return the table of Message
	 */
	fr.umlv.ir3.corba.sguincha.td2.Message[] getMessages ();

	/**
	 * @param title
	 * @return if the remove operation successfully or not
	 */
	boolean removeMessage (String title);
} // interface ForumOperations
