package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/ForumOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

public interface ForumOperations
{
	String theme ();

	String moderator ();

	boolean postMessage (fr.umlv.ir3.corba.sguincha.td2.Message m);

	fr.umlv.ir3.corba.sguincha.td2.Message getMessage (String title);

	fr.umlv.ir3.corba.sguincha.td2.Message[] getMessages ();

	boolean removeMessage (String title);
} // interface ForumOperations
