package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/MessageHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

abstract public class MessageHelper
{
	private static String	_id	= "IDL:td2/Message/Message:1.0";

	/**
	 * @param a
	 * @param that
	 */
	public static void insert (org.omg.CORBA.Any a, fr.umlv.ir3.corba.sguincha.td2.Message that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out , that);
		a.read_value (out.create_input_stream () , type ());
	}

	/**
	 * @param a
	 * @return a Message
	 */
	public static fr.umlv.ir3.corba.sguincha.td2.Message extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode	__typeCode	= null;
	private static boolean					__active	= false;

	/**
	 * @return a TypeCode
	 */
	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			synchronized (org.omg.CORBA.TypeCode.class)
			{
				if (__typeCode == null)
				{
					if (__active)
					{
						return org.omg.CORBA.ORB.init ().create_recursive_tc (_id);
					}
					__active = true;
					org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					_tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
					_members0 [0] = new org.omg.CORBA.StructMember ("title", _tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
					_members0 [1] = new org.omg.CORBA.StructMember ("author", _tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
					_members0 [2] = new org.omg.CORBA.StructMember ("date", _tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
					_members0 [3] = new org.omg.CORBA.StructMember ("body", _tcOf_members0, null);
					__typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (fr.umlv.ir3.corba.sguincha.td2.MessageHelper.id () , "Message" , _members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	/**
	 * @return rhe String ID
	 */
	public static String id ()
	{
		return _id;
	}

	/**
	 * @param istream
	 * @return a Message
	 */
	public static fr.umlv.ir3.corba.sguincha.td2.Message read (org.omg.CORBA.portable.InputStream istream)
	{
		fr.umlv.ir3.corba.sguincha.td2.Message value = new fr.umlv.ir3.corba.sguincha.td2.Message ();
		value.title = istream.read_string ();
		value.author = istream.read_string ();
		value.date = istream.read_string ();
		value.body = istream.read_string ();
		return value;
	}

	/**
	 * @param ostream
	 * @param value
	 */
	public static void write (org.omg.CORBA.portable.OutputStream ostream, fr.umlv.ir3.corba.sguincha.td2.Message value)
	{
		ostream.write_string (value.title);
		ostream.write_string (value.author);
		ostream.write_string (value.date);
		ostream.write_string (value.body);
	}

}
