package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/MessageSetHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15
 * octobre 2004 14 h 06 CEST
 */

abstract public class MessageSetHelper
{
	private static String	_id	= "IDL:td2/MessageSet:1.0";

	public static void insert (org.omg.CORBA.Any a, fr.umlv.ir3.corba.sguincha.td2.Message[] that)
	{
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
		a.type (type ());
		write (out , that);
		a.read_value (out.create_input_stream () , type ());
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Message[] extract (org.omg.CORBA.Any a)
	{
		return read (a.create_input_stream ());
	}

	private static org.omg.CORBA.TypeCode	__typeCode	= null;

	synchronized public static org.omg.CORBA.TypeCode type ()
	{
		if (__typeCode == null)
		{
			__typeCode = fr.umlv.ir3.corba.sguincha.td2.MessageHelper.type ();
			__typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0 , __typeCode);
			__typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (fr.umlv.ir3.corba.sguincha.td2.MessageSetHelper.id () , "MessageSet" , __typeCode);
		}
		return __typeCode;
	}

	public static String id ()
	{
		return _id;
	}

	public static fr.umlv.ir3.corba.sguincha.td2.Message[] read (org.omg.CORBA.portable.InputStream istream)
	{
		fr.umlv.ir3.corba.sguincha.td2.Message value[] = null;
		int _len0 = istream.read_long ();
		value = new fr.umlv.ir3.corba.sguincha.td2.Message [_len0];
		for (int _o1 = 0; _o1 < value.length; ++_o1)
			value [_o1] = fr.umlv.ir3.corba.sguincha.td2.MessageHelper.read (istream);
		return value;
	}

	public static void write (org.omg.CORBA.portable.OutputStream ostream, fr.umlv.ir3.corba.sguincha.td2.Message[] value)
	{
		ostream.write_long (value.length);
		for (int _i0 = 0; _i0 < value.length; ++_i0)
			fr.umlv.ir3.corba.sguincha.td2.MessageHelper.write (ostream , value [_i0]);
	}

}
