package fr.umlv.ir3.corba.sguincha.td2;

/**
 * fr/umlv/ir3/corba/sguincha/td2/Message.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from IDL/Forum.idl vendredi 15 octobre
 * 2004 14 h 06 CEST
 */

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
	public String	title	= null;
	public String	author	= null;
	public String	date	= null;
	public String	body	= null;

	public Message ()
	{
	} // ctor

	public Message (String _title, String _author, String _date, String _body)
	{
		title = _title;
		author = _author;
		date = _date;
		body = _body;
	} // ctor

} // class Message
