module forum {
	struct TextMessage {
		string title;
		string author;
		string date;
		string body;
	};
	
	struct AudioMessage {
		string title;
		string author;
		string date;
		string body;
		string paroles;
	};
	
	typedef sequence <any> MessageSet;
	exception Reject { string message; };
	
	interface Forum {
		readonly attribute string theme;
		readonly attribute string moderator;
		boolean postMessage(in string title, in any m) raises (Reject);
		any getMessage(in string title) raises (Reject);
		MessageSet getMessages();
		void removeMessage(in string title) raises (Reject);
		void getInfo (out string theme, out string moderator, out long size);
	};
};

